apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: product
    version: v1
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: product
        version: v1
    spec:
      containers:
      - image: product:1.0
        name: product
        ports:
        - containerPort: 8080
        env:
          - name: "deployment.version"
            value: "v1"
        resources: {}
status: {}
